name: "TAR (Push)"

on:
  - push

env:
  domain: "${{ github.server_url }}"
  owner: "${{ github.repository_owner }}"
  repo: "${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - run: echo "CMF=$( echo '${{ env.repo }}' | awk -F '[/-]' '{ print $2 }' )" >> $GITHUB_ENV
        shell: bash
      - run: echo "NAME=$( echo '${{ env.repo }}' | awk -F '${{ env.CMF }}-' '{ print $2 }' )" >> $GITHUB_ENV
        shell: bash
      - uses: ghastore/store-tar-build@main
        with:
          git_repo_src: "${{ env.domain }}/${{ env.repo }}.git"
          git_repo_dst: "${{ env.domain }}/${{ env.owner }}-${{ env.CMF }}/${{ env.NAME }}.git"
          git_user: "${{ secrets.BOT_GITHUB_NAME }}"
          git_email: "${{ secrets.BOT_GITHUB_EMAIL }}"
          git_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
